### ISSUE TITLE
Convert testcluster to use robot framework

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-testcluster#323]
- [x] Port functional tests
- [x] Port performance tests
- [x] Port listener tests
- [x] Green functional test run
- [x] Running in Jenkins Job
- [x] Rebase master onto branch

**Comment by sethrosetter** [comment]
Closed via https://github.com/couchbaselabs/sync-gateway-testcluster/commit/1e01f1b5522553b0f42c32b4343cd83b19d5b7bd
