### ISSUE TITLE
[DB Online / Offline] Functional Test Scenarios

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/sync-gateway-testcluster#99]
- [x] Scenario 1 (See NOTES 1) - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/78

Start SG with bucket in online state (no offline config property), make REST API calls against DB - expected result RAST API calls are successful
- [x] Scenario 2 (See NOTES 1) - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/79

Start SG with bucket in online state setting Db 'offline' config property to false),  make REST API calls against DB - expected result REST API calls are successful
- [x] Scenario 3 (See NOTES 1) - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/80

With DB in online state, no active REST API calls, take DB offline, expected result _offline call returns status 200, make REST API calls against DB, expected result returns status 503.
- [x] Scenario 4 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/81

With DB in online state, make REST API call to get DB runtime details /db/, expected result 'state' property with value 'Online' is returned.
- [x] Scenario 5 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/82

With DB in online state, active _changes (try longpoll, continuous, websockets feeds), take DB offline, expected result _offline call returns status 200, all active changes feeds are closed in a controlled way returning to client, longpoll should return a valid last sequence value.
- [x] Scenario 6 (See NOTES 1) - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/83

Start SG with bucket in offline state setting DB 'offline' config property to true),  make REST API calls against DB - expected result RAST API calls fail with 503
- [ ] Scenario 7 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/84

With DB in offline state, make REST API calls against DB for supported offline operations, GET db status, PUT DB config, expected result calls should return status 200.
- [x] Scenario 8 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/85

With DB in offline state, make REST API call to get DB runtime details /db/, expected result 'state' property with value 'Offline' is returned.
- [x] Scenario 9 (See NOTES 1) - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/86

With DB in offline state, make REST API _online call against DB,  expected result _online call should return status 200.  Make REST API calls against DB - expected result REST API calls are successful
- [ ] Scenario 10 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/87

With DB in offline state, make REST API _online call against DB with a delay of 15 soconds,  expected result _online call should return status 200.  Make REST API calls against DB - expected result REST API calls will fail status 503. Wait until 15 second delay has elapsed, make REST API calls against DB - expected result REST API calls will succeed with status 200.
- [ ] Scenario 11 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/88

With DB in online state, put a large number of docs (enough to cause _resync to run for 10-15 seconds), put DB offline, run _resync, attempt to bring DB online while _resync is running, expected result _online will fail with status 503, when _resync is complete, attempt to bring DB _online, expected result _online will succeed, return status 200.
- [ ] Scenario 12 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/89

While DB is running _resync make REST API calls against DB for supported offline operations, GET db status, PUT DB config, expected result calls should return status 200.
- [ ] Scenario 13 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/90

With DB running a _resync, make REST API call to get DB runtime details /db/, expected result 'state' property with value 'Resyncing' is returned.
- [ ] Scenario 14 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/91

With DB in online state, put new valid DB config, take DB offline, bring DB online. Expected result DB has new config applied.
- [ ] Scenario 15 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/92

With DB in offline state, put new valid DB config, bring DB online. Expected result DB has new config applied.
- [x] Scenario 16 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/93

With DB in online state, put new invalid DB config, take DB offline, bring DB online. Expected result DB fails to come online, error status is returned.
- [ ] Scenario 17 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/94

With DB in offline state, put new invalid DB config, bring DB online. Expected result DB fails to come online, error status is returned.
- [ ] Scenario 18 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/95

Configure WebHooks for online/offline events, With DB in online State, take DB offline, expected result a DBOffline event is sent to the configured webhook endpoint
- [ ] Scenario 19 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/96

Configure WebHooks for online/offline events, With DB in offline State, take DB online, expected result a DBOnline event is sent to the configured webhook endpoint
- [x] Scenario 20 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/97

With DB in online state, simulate loss of TAP feed, expected result the DB should be taken offline. 
- [ ] Scenario 21 - https://github.com/couchbaselabs/sync-gateway-testcluster/issues/98

Configure WebHooks for online/offline events, with DB in online state, simulate loss of TAP feed, expected result the DB should be taken offline, a DBOffline event is sent to the configured webhook endpoint

NOTES:
1. We are scanning many of the /db/ endpoints as pass criteria for the scenarios. Below are the REST calls that we are currently exercising in the scenario. We expect the call to be successful if the db is online or 503 if it is offline:
### REST calls we are hitting 
- PUT /{db}/_role/{name}
- GET /{db}/_role
- GET /{db}/_role/{name}
- PUT /{db}/_user/{name}
- GET /{db}/_user
- GET /{db}/_user/{name}
- GET /{db}
- PUT /{db}/{name}
- GET /{db}/{name}
- POST /{db}/_bulk_docs
- GET /{db}/_all_docs
- GET /{db}/_changes

We are not currently hitting all of the db endpoint as our framework does not yet support them. We are working on getting these implemented as soon as possible but we want to be explicit of the endpoints that are not currently being hit. 

### MISSING /db/ REST calls
- GET /{db}/_session/{session-id}
- POST /{db}/_session
- DELETE /{db}/_session/{session-id}
- DELETE /{db}/_user/{name}/_session/{session-id}
- DELETE /{db}/_user/{name}/_session
- DELETE /{db}/_user/{name}
- POST /{db}/_role/
- DELETE /{db}/_role/{name}
- POST /{db}/_all_docs
- POST /{db}/_bulk_get
- DELETE /{db}/{doc}
- PUT /{db}/{doc}/{attachment}
- GET /{db}/{doc}/{attachment}
- PUT /{db}/{local-doc-id}
- GET /{db}/{local-doc-id}
- DELETE /{db}/{local-doc-id}
- POST /{db}/_facebook_token
- POST /{db}/_persona_assertion
- POST /{db}

Please let us know ASAP if we need to prioritize implementing calls to these with regard to the feature.

**Comment by sethrosetter** [comment]
An update. We are currently blocked on #95 #96 #97 #21 due to missing web hook support and TAP feed loss detection

**Comment by sethrosetter** [comment]
Also, waiting to hear from @adamcfraser about the tests regarding dynamic reloading of db config #91 #92 #93 #94

**Comment by zgramana** [comment]
The highest priority functional test currently missing is `GET /{db}/{local-doc-id}`. I'd add `POST /{db}/_bulk_get` as a stretch.
